apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/kubernetes-sigs/gateway-api/config/crd/?ref=v1.3.0
  - https://github.com/envoyproxy/gateway/releases/download/v1.5.1/envoy-gateway-crds.yaml

patches:
  # Drop resources that shouldn't be added to upstream control planes yet
  # Gateway API resources
  - patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: grpcroutes.gateway.networking.k8s.io
  - patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: referencegrants.gateway.networking.k8s.io
  # Envoy gateway resources
  - patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: envoyextensionpolicies.gateway.envoyproxy.io
  - patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: envoypatchpolicies.gateway.envoyproxy.io
  - patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: envoyproxies.gateway.envoyproxy.io
  - patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: clienttrafficpolicies.gateway.envoyproxy.io
