apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/kubernetes-sigs/gateway-api/config/crd/?ref=v1.2.1

patches:
  # Drop ReferenceGrants for now
  - patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: referencegrants.gateway.networking.k8s.io
