apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- service_account.yaml
images:
- name: controller
  newName: network-services-operator
  newTag: latest
configMapGenerator:
- name: config
  files:
    - config.yaml
buildMetadata:
  - managedByLabel

labels:
  - pairs:
      app.kubernetes.io/part-of: network-services-operator
    includeSelectors: true
    includeTemplates: true
