kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: networking.datumapis.com
        kind: "HTTPProxy"
        version: "v1alpha"
      metricNamePrefix: datum_cloud_networking_http_proxy
      labelsFromPath:
        name: [metadata, name]
        namespace: [metadata, namespace]
      metrics:
      - name: "owner"
        help: "Owner information"
        errorLogV: 10
        each:
          type: Info
          info:
            path: [metadata,ownerReferences]
            labelsFromPath:
              owner_kind: [kind]
              owner_name: [name]
              owner_uid: [uid]
              controller: [controller]
      - name: "info"
        help: "HTTPProxy information"
        each:
          type: Info
          info:
            labelsFromPath:
              uid: [metadata, uid]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "status_condition"
        help: "The current status conditions of the HTTP Proxy"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              condition: [type]
              reason: [reason]
              status: [status]
            valueFrom: [status]
      - name: "custom_hostname"
        help: "Custom hostname defined on the proxy"
        errorLogV: 10
        each:
          type: Info
          info:
            path: [spec,hostnames]
            labelsFromPath:
              hostname: []
