apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: network-services-metrics
    files:
      - network-bindings.yaml
      - network-contexts.yaml
      - network-policies.yaml
      - networks.yaml
      - subnet-claims.yaml
      - subnets.yaml
      - locations.yaml
      - gateways.yaml
      - httpproxies.yaml
      - domains.yaml
      - trafficprotectionpolicies.yaml
    options:
      labels:
        telemetry.miloapis.com/resource-metrics-config: "true"
