kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: networking.datumapis.com
        kind: NetworkBinding
        version: v1alpha
      metricNamePrefix: "datum_cloud_network_binding"
      labelsFromPath:
        namespace: [metadata, namespace]
        name: [metadata, name]
        network_name: [spec, network, name]
        network_namespace: [spec, network, namespace]
      metrics:
        - name: "info"
          help: "Information about network binding"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
        - name: "status_condition"
          help: "The current status conditions of the network binding"
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                condition: [type]
                reason: [reason]
                status: [status]
              valueFrom: [status]
