apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: networking.datumapis.com-gateway-admin
  annotations:
    kubernetes.io/display-name: Gateway Admin
    kubernetes.io/description: "Full access to gateway resources"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: networking.datumapis.com-gateway-viewer
  includedPermissions:
    - gateway.networking.k8s.io/gateways.create
    - gateway.networking.k8s.io/gateways.update
    - gateway.networking.k8s.io/gateways.patch
    - gateway.networking.k8s.io/gateways.delete
    - gateway.networking.k8s.io/httproutes.create
    - gateway.networking.k8s.io/httproutes.update
    - gateway.networking.k8s.io/httproutes.patch
    - gateway.networking.k8s.io/httproutes.delete
    - gateway.envoyproxy.io/backends.create
    - gateway.envoyproxy.io/backends.update
    - gateway.envoyproxy.io/backends.patch
    - gateway.envoyproxy.io/backends.delete
    - gateway.envoyproxy.io/backendtrafficpolicies.create
    - gateway.envoyproxy.io/backendtrafficpolicies.update
    - gateway.envoyproxy.io/backendtrafficpolicies.patch
    - gateway.envoyproxy.io/backendtrafficpolicies.delete
    - gateway.envoyproxy.io/httproutefilters.create
    - gateway.envoyproxy.io/httproutefilters.update
    - gateway.envoyproxy.io/httproutefilters.patch
    - gateway.envoyproxy.io/httproutefilters.delete
    - gateway.envoyproxy.io/securitypolicies.create
    - gateway.envoyproxy.io/securitypolicies.update
    - gateway.envoyproxy.io/securitypolicies.patch
    - gateway.envoyproxy.io/securitypolicies.delete
    - discovery.k8s.io/endpointslices.create
    - discovery.k8s.io/endpointslices.update
    - discovery.k8s.io/endpointslices.patch
    - discovery.k8s.io/endpointslices.delete
    - networking.datumapis.com/httpproxies.create
    - networking.datumapis.com/httpproxies.update
    - networking.datumapis.com/httpproxies.patch
    - networking.datumapis.com/httpproxies.delete
