apiVersion: apiserver.config.datumapis.com/v1alpha1
kind: NetworkServicesOperator
gateway:
  targetDomain: prism.e2e.env.datum.net
  permittedTLSOptions:
    gateway.networking.datumapis.com/certificate-issuer: []
    downstreamGatewayClassName: datum-downstream-gateway-e2e
downstreamResourceManagement:
  kubeconfigPath: /etc/downstream-cluster/kubeconfig
