namespace: network-services-operator-system
namePrefix: network-services-operator-

resources:
  - ../crd
  - ../rbac
  - ../rbac_deployment
  - ../manager


configMapGenerator:
  - name: config
    behavior: replace
    files:
      - config.yaml

patches:
  - target:
      kind: Deployment
      name: controller-manager
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: controller-manager
      spec:
        template:
          spec:
            containers:
              - name: manager
                volumeMounts:
                - name: downstream-cluster-kubeconfig
                  mountPath: /etc/downstream-cluster
            volumes:
              - name: downstream-cluster-kubeconfig
                secret:
                  secretName: downstream-cluster-kubeconfig
