namespace: network-services-operator-system
namePrefix: network-services-operator-

resources:
  - ../crd
  - ../rbac
  - ../manager


configMapGenerator:
  - name: config
    behavior: replace
    files:
      - config.yaml

patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --downstream-kubeconfig=/etc/downstream-cluster/kubeconfig
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: downstream-cluster-kubeconfig
          mountPath: /etc/downstream-cluster
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: downstream-cluster-kubeconfig
          secret:
            secretName: downstream-cluster-kubeconfig
    target:
      kind: Deployment
      name: controller-manager
