apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: network-services-operator
    app.kubernetes.io/component: extension-server
    app.kubernetes.io/managed-by: kustomize
  name: envoy-gateway-extension-server
  namespace: system
