# permissions for end users to edit networks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: network-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: network-editor-role
rules:
- apiGroups:
  - networking.datumapis.com
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.datumapis.com
  resources:
  - networks/status
  verbs:
  - get
