# permissions for end users to view networkcontexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: network-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkcontext-viewer-role
rules:
- apiGroups:
  - networking.datumapis.com
  resources:
  - networkcontexts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.datumapis.com
  resources:
  - networkcontexts/status
  verbs:
  - get
