package words

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
)

// Create a deterministic string using two english words and 5 hash-derived
// characters (no vowels, no ambiguous chars) from a seed string.
//
// This yields an output space of roughly 330 trillion strings:
// - 5-char alphabet component: 45M
// - ~2700 words, picking 2 at a time (ordered, permutation): 7.4M
// - 45M * 7.4M ~= 330T
//
// NB: A seed will generate the same return value each time. However,
// if the word list or charset is changed below, then strings
// generated after that will likely be different given that same seed.
func WordsAndEntropy(suffix, seedString string) string {
	digest := sha256.Sum256([]byte(seedString))
	charset := "bcdfghjkmnpqrstvwxyz23456789"

	hashChars := make([]byte, 5)
	for i := range hashChars {
		hashChars[i] = charset[int(digest[i])%len(charset)]
	}

	word1Index := int(binary.BigEndian.Uint16(digest[5:7])) % len(DictionaryWords)
	word2Index := int(binary.BigEndian.Uint16(digest[7:9])) % len(DictionaryWords)
	word1 := DictionaryWords[word1Index]
	word2 := DictionaryWords[word2Index]

	return fmt.Sprintf("%s-%s-%s%s", word1, word2, string(hashChars), suffix)
}

var DictionaryWords = []string{
	"stark", "weave", "clear", "donut", "ham", "sat", "tracks", "lost", "crown", "dizzy",
	"gummy", "raven", "transit", "camp", "flow", "flake", "realm", "strain", "milk", "most",
	"lunch", "noble", "shrink", "toy", "module", "stop", "mouth", "object", "shall", "van",
	"decade", "text", "facet", "spite", "bath", "twirl", "worry", "finger", "done", "swim",
	"unit", "person", "pride", "village", "door", "scrap", "strife", "during", "drive", "jade",
	"pan", "pledge", "trap", "variable", "critic", "tackle", "rotate", "shine", "prop", "show",
	"input", "switch", "tweed", "dodge", "flung", "timber", "weigh", "located", "hold", "iron",
	"jeans", "seize", "unreal", "varied", "gold", "crater", "infra", "petite", "sonic", "fancy",
	"health", "poker", "unable", "yellow", "earn", "them", "normal", "satin", "tool", "user",
	"husky", "lean", "tonic", "turtle", "unmarried", "besides", "fetch", "reckon", "either", "flock",
	"gadget", "govern", "great", "omen", "stall", "wolf", "honest", "fail", "term", "struck",
	"yet", "pink", "crank", "stuff", "throw", "world", "hush", "student", "wagon", "jean",
	"oath", "shell", "under", "worse", "stay", "verb", "flick", "knit", "perch", "waste",
	"longer", "firm", "horse", "lynx", "sum", "usage", "choice", "ford", "late", "link",
	"pack", "warm", "hyena", "leak", "marry", "embed", "myself", "reed", "resort", "carbon",
	"casual", "flight", "last", "dread", "pint", "steak", "margin", "diary", "gleam", "pencil",
	"suds", "walnut", "typing", "lovely", "low", "veto", "ward", "fully", "pop", "their",
	"account", "farmer", "groove", "loop", "lawyer", "bone", "blink", "clash", "crisp", "log",
	"string", "wade", "tariff", "optic", "singer", "regard", "blend", "every", "graph", "guilt",
	"sewer", "result", "stain", "king", "shop", "pendulum", "scalp", "total", "trance", "coffee",
	"except", "lake", "out", "trial", "budget", "rarely", "easy", "look", "brush", "diver",
	"obtain", "circle", "claim", "silicon", "hundred", "motto", "sauna", "soccer", "spoke", "thrill",
	"rich", "birch", "dairy", "phone", "shout", "ski", "custom", "devote", "luck", "rule",
	"spent", "wheat", "rating", "writer", "empty", "plaid", "rust", "strict", "joke", "mint",
	"stride", "ever", "socket", "star", "ignore", "our", "deal", "left", "various", "weasel",
	"advanced", "cold", "giant", "flat", "list", "range", "reap", "super", "middle", "chart",
	"glee", "nest", "unwise", "cabinet", "luxury", "glen", "gull", "helium", "muster", "ministry",
	"mile", "brain", "erase", "found", "hover", "reel", "toward", "very", "grill", "patch",
	"sun", "temper", "subtle", "work", "siege", "slack", "speed", "walker", "knew", "week",
	"plow", "set", "sting", "minute", "ace", "rice", "chord", "comma", "best", "join",
	"spend", "nature", "away", "fine", "hill", "mold", "ray", "servant", "commit", "heat",
	"myth", "over", "picnic", "preach", "salmon", "sphere", "decay", "overt", "period", "pest",
	"steep", "touch", "pose", "gloom", "prince", "sharp", "spill", "tease", "rug", "sunny",
	"balance", "policy", "cost", "ours", "spider", "client", "pursuit", "trusts", "math", "chair",
	"garden", "ought", "stance", "tutor", "goes", "loan", "oval", "spark", "teach", "smooth",
	"vampire", "buffer", "museum", "power", "make", "haunt", "setting", "spike", "zombie", "circuit",
	"food", "siren", "slept", "spouse", "academy", "lesson", "lights", "cross", "key", "twig",
	"portal", "waiting", "jump", "lucid", "reward", "mightily", "back", "cope", "nail", "such",
	"gorge", "bottle", "plot", "candle", "token", "alleged", "port", "polar", "sour", "whip",
	"feed", "inbox", "lace", "train", "seat", "review", "palace", "within", "tale", "dogma",
	"extra", "label", "prove", "similar", "anybody", "than", "eerie", "inter", "remit", "shuffle",
	"skip", "solve", "trigger", "entry", "reach", "raising", "rising", "penalty", "prefer", "trek",
	"long", "shore", "whose", "zoom", "airport", "measure", "each", "clock", "dryer", "slang",
	"closely", "hardly", "hug", "merger", "mild", "relax", "right", "spear", "value", "brink",
	"knight", "nurse", "red", "twice", "dancer", "handy", "lever", "pedal", "strand", "relate",
	"speaks", "noisy", "one", "self", "plunge", "repel", "void", "denied", "home", "sink",
	"breed", "theme", "spruce", "moving", "stem", "wing", "float", "grove", "howl", "leaf",
	"pave", "scan", "see", "squad", "hung", "blast", "lurk", "muzzle", "calcium", "career",
	"length", "form", "board", "hoping", "moral", "stage", "violin", "just", "gaze", "ignite",
	"shawl", "assured", "call", "wall", "heal", "mammal", "nasal", "off", "recruit", "unaware",
	"band", "want", "wish", "beech", "gecko", "wealth", "soul", "clang", "phase", "born",
	"cheek", "grin", "point", "quick", "rhythm", "safety", "tame", "receive", "scale", "tycoon",
	"universe", "violet", "vital", "itself", "letter", "main", "plug", "bundle", "unlike", "versus",
	"this", "guppy", "often", "vehicle", "chip", "give", "thus", "crowd", "vendor", "must",
	"sake", "route", "mimic", "theory", "think", "broker", "clasp", "folly", "reign", "resume",
	"serve", "severe", "enough", "estate", "impose", "lime", "bond", "exit", "near", "poll",
	"cocoa", "guild", "hurdle", "hybrid", "minus", "rigid", "trade", "fort", "ring", "straight",
	"track", "vale", "win", "castle", "fabric", "ship", "ghost", "launch", "pepper", "proud",
	"mirror", "outcome", "equip", "ice", "laugh", "rub", "tray", "apparent", "timing", "younger",
	"major", "situated", "study", "unhappy", "driver", "spoken", "nice", "draft", "eagle", "quart",
	"she", "static", "totem", "paying", "comic", "sense", "dish", "five", "same", "cycle",
	"record", "visual", "father", "weak", "remedy", "skill", "valve", "worth", "stove", "bottom",
	"path", "donor", "large", "maple", "march", "tooth", "half", "roof", "went", "color",
	"micro", "offer", "shake", "shock", "soon", "incur", "strap", "headed", "kelp", "loose",
	"settle", "warn", "keep", "camel", "essay", "force", "scary", "silver", "deep", "film",
	"issue", "solar", "even", "grape", "humor", "there", "try", "variety", "fence", "trend",
	"grey", "neat", "virtue", "find", "frost", "growl", "public", "rhino", "married", "simply",
	"less", "grown", "photo", "session", "state", "sweet", "fish", "foggy", "kiss", "pill",
	"stone", "odds", "exist", "plant", "slim", "thaw", "uneven", "ticket", "tank", "candy",
	"decoy", "erupt", "fruit", "outer", "prior", "scare", "days", "told", "event", "mural",
	"sob", "stale", "submit", "magic", "stole", "ember", "gourd", "neither", "pail", "solely",
	"ivory", "feel", "kept", "saddle", "shelf", "citizen", "lotus", "recall", "profit", "update",
	"trip", "crude", "eater", "rescue", "dove", "flare", "import", "penguin", "shrug", "tide",
	"humble", "thrust", "some", "petal", "sweep", "gift", "walk", "error", "lung", "orchard",
	"routine", "tap", "unfair", "backing", "salvage", "server", "transfer", "seed", "score", "slab",
	"tea", "will", "hello", "series", "snug", "tag", "heel", "since", "former", "lord",
	"wash", "hard", "wave", "image", "finish", "zone", "flank", "heath", "behalf", "global",
	"cave", "view", "nomad", "sad", "slight", "speech", "mice", "happen", "secure", "giddy",
	"nothing", "oak", "recover", "sheet", "squat", "risk", "glass", "index", "light", "noodle",
	"sofa", "chat", "care", "bunch", "owl", "sea", "syrup", "anyone", "finer", "ranch",
	"today", "canal", "pot", "unusual", "lot", "rapid", "trouble", "write", "golem", "say",
	"galaxy", "wholly", "civil", "flash", "hydro", "hyphen", "neon", "though", "thrive", "truth",
	"built", "fifth", "melee", "sport", "turkey", "twin", "gloss", "kernel", "print", "reply",
	"scene", "reject", "plus", "clerk", "heart", "heron", "husband", "replay", "tenant", "repair",
	"shade", "snarl", "dense", "flush", "labor", "potter", "sung", "wreak", "rail", "comet",
	"drawn", "hare", "niche", "nudge", "parody", "slash", "case", "operate", "sneak", "space",
	"vivid", "witch", "behind", "camera", "talk", "wind", "clout", "dress", "humus", "numb",
	"proof", "shot", "limb", "tough", "via", "wool", "behave", "bush", "kneel", "prefix",
	"common", "others", "mate", "top", "online", "acid", "wet", "island", "heap", "rave",
	"river", "system", "whale", "trader", "boss", "oblique", "raft", "together", "sand", "monthly",
	"gone", "primary", "swift", "option", "phrase", "then", "scope", "tear", "tortoise", "utter",
	"number", "neglect", "target", "master", "book", "sage", "fewer", "house", "nobly", "query",
	"salad", "spring", "activity", "courtesy", "game", "upon", "pony", "satisfy", "unripe", "roll",
	"type", "novel", "danger", "dwarf", "inane", "lap", "pig", "lantern", "fear", "lead",
	"hour", "brake", "imbue", "order", "retail", "stamp", "deputy", "fallen", "glad", "tent",
	"powder", "quiet", "retain", "seller", "shaped", "bowl", "duke", "hope", "rate", "dance",
	"puma", "live", "cause", "dwell", "moat", "ruby", "volume", "cloak", "fried", "known",
	"parrot", "dust", "science", "weld", "change", "corps", "enable", "yeah", "frank", "jewel",
	"soak", "terrain", "indeed", "boast", "gland", "stun", "swept", "patio", "sound", "picked",
	"pie", "calm", "crop", "hall", "broth", "return", "tall", "basin", "blown", "fuzzy",
	"icing", "stood", "hair", "jeep", "basil", "muffin", "trim", "offset", "song", "sure",
	"output", "ready", "soot", "solving", "sudden", "apron", "elite", "shiver", "wedge", "mull",
	"between", "worker", "ferry", "piece", "these", "bike", "many", "ridge", "neck", "pit",
	"swarm", "unwanted", "buried", "soil", "berry", "emcee", "oil", "pelican", "pigeon", "quilt",
	"sixty", "fused", "hail", "jacket", "radio", "raise", "ritual", "spread", "waist", "sent",
	"frown", "heir", "unknown", "fourth", "fast", "orange", "pilot", "rein", "trail", "mask",
	"used", "drawl", "hymn", "kiosk", "script", "success", "logo", "nephew", "north", "pawn",
	"survey", "intend", "vinyl", "tiny", "graze", "guise", "loft", "onset", "other", "use",
	"warp", "peak", "blame", "defer", "enter", "silent", "meat", "focus", "match", "snare",
	"cacao", "sell", "china", "orca", "ramp", "torch", "bright", "green", "mix", "pub",
	"sister", "wisdom", "lately", "opening", "paid", "post", "net", "tin", "talent", "knock",
	"snail", "vague", "caught", "host", "pole", "block", "chief", "debut", "final", "music",
	"money", "pen", "place", "planet", "popcorn", "sector", "shallow", "opal", "lion", "pasta",
	"sustain", "sway", "worn", "becoming", "rank", "clamp", "unborn", "costly", "entire", "level",
	"muse", "nap", "sash", "setup", "sonar", "stake", "cafe", "prod", "count", "shun",
	"buttons", "formal", "bliss", "hurl", "meter", "seldom", "amazing", "chain", "stair", "yes",
	"trucks", "weekly", "aged", "ribbon", "velvet", "region", "soup", "drill", "groom", "seven",
	"origin", "lady", "rose", "fling", "glory", "smell", "soar", "stream", "struggle", "fault",
	"ideal", "ladle", "potato", "school", "sheer", "swell", "anymore", "need", "lawn", "store",
	"support", "tomato", "suit", "cheat", "prairie", "water", "which", "appeal", "stable", "belt",
	"vast", "carry", "matrix", "ninja", "party", "plenty", "burst", "time", "tree", "when",
	"quote", "urban", "step", "broad", "cream", "tower", "buying", "cover", "flood", "flute",
	"sight", "tight", "ultra", "wise", "beach", "brick", "metal", "staff", "nearby", "famed",
	"scissors", "jack", "ride", "town", "brook", "guide", "serious", "spur", "way", "kick",
	"hunch", "quirk", "sheep", "surprise", "treat", "zipper", "device", "gouge", "layer", "rouge",
	"seeing", "zip", "warmth", "enjoy", "grate", "guard", "visor", "wonder", "losing", "signed",
	"sold", "streak", "tried", "groan", "street", "root", "basket", "lilac", "probe", "twenty",
	"victory", "what", "chase", "rubber", "thanks", "goal", "joint", "ozone", "puff", "sketch",
	"nearly", "coat", "flask", "gnash", "notice", "remote", "your", "delta", "gem", "leach",
	"tax", "exalt", "gutter", "plate", "effort", "ending", "purge", "rectify", "visa", "inn",
	"lard", "leap", "pouch", "third", "thumb", "dawn", "spit", "union", "habit", "manage",
	"obey", "coach", "motor", "shed", "pin", "plutonium", "sunset", "autumn", "chunk", "foray",
	"lasso", "leather", "upset", "blunt", "moist", "rubble", "shaft", "smoke", "strong", "octopus",
	"sniff", "vigil", "else", "lava", "shape", "engage", "pity", "thin", "cabin", "dozen",
	"hazel", "herd", "narrow", "vain", "past", "coral", "fairy", "logic", "surge", "twist",
	"valor", "reform", "quota", "too", "station", "trades", "farm", "curve", "hump", "plod",
	"press", "rotor", "select", "wild", "gauge", "recycle", "birth", "opt", "quantity", "dose",
	"foot", "vary", "hound", "remove", "satire", "strive", "share", "silly", "spec", "fact",
	"soft", "grass", "editor", "gauze", "lizard", "mead", "model", "smile", "topic", "copy",
	"gave", "blade", "grab", "month", "needle", "silk", "brand", "pants", "rope", "rough",
	"scroll", "sadness", "signal", "plan", "room", "story", "style", "come", "deny", "geek",
	"hull", "ledge", "rural", "surface", "wit", "toast", "volcano", "leg", "mustard", "nut",
	"poach", "facing", "nobody", "hire", "plane", "romance", "sit", "oasis", "slice", "army",
	"site", "leave", "straw", "warned", "junior", "saving", "huge", "none", "moment", "stand",
	"lark", "slow", "cargo", "furry", "guest", "plump", "tip", "civic", "stereo", "vase",
	"virtual", "factor", "income", "runner", "news", "cheer", "inlet", "niece", "peach", "ton",
	"trunk", "why", "name", "craze", "eight", "excel", "given", "gown", "owner", "predict",
	"shut", "disco", "group", "havoc", "magnet", "muscle", "scout", "throat", "area", "note",
	"cliff", "hack", "truck", "you", "pattern", "scheme", "sort", "doing", "mercy", "ninth",
	"peace", "render", "busy", "gene", "fauna", "grasp", "hazard", "relay", "run", "move",
	"ruin", "spiral", "vegan", "winner", "studio", "tone", "dough", "puppy", "saga", "sleep",
	"suggest", "would", "arrival", "haven", "moan", "pirate", "winter", "adequate", "largely", "fern",
	"rode", "fresh", "maid", "notch", "slam", "spicy", "tablet", "ease", "earth", "proper",
	"razor", "resent", "legacy", "notion", "arrow", "joust", "pizza", "reader", "smart", "eager",
	"short", "slot", "spoon", "latter", "happy", "heave", "sized", "pull", "year", "break",
	"grain", "inject", "lonely", "queue", "stare", "chosen", "here", "brave", "cough", "moor",
	"penny", "modify", "bless", "forum", "lorry", "mud", "memory", "tennis", "glare", "pay",
	"secret", "sequence", "grim", "tunnel", "bite", "dark", "fell", "stump", "hotel", "merry",
	"pocket", "rot", "shack", "vent", "verse", "pond", "sigh", "brisk", "broil", "creek",
	"glide", "rake", "whole", "road", "roar", "salute", "snap", "trace", "read", "napkin",
	"shift", "swing", "lush", "office", "precis", "slipper", "tack", "halo", "iris", "dirt",
	"much", "parcel", "posting", "core", "crane", "south", "divide", "jazz", "bound", "cloud",
	"season", "valley", "medical", "dial", "full", "rest", "catch", "limit", "pillow", "meal",
	"carve", "react", "round", "sixth", "pile", "grocery", "sample", "temple", "those", "tunic",
	"battery", "forest", "dual", "evade", "feast", "harp", "stub", "swap", "tulip", "uncle",
	"guess", "naval", "semester", "small", "watch", "tempo", "achieved", "does", "okay", "bread",
	"delay", "source", "spare", "vow", "chance", "coal", "wait", "elect", "inner", "lamp",
	"lease", "ounce", "rocket", "sentence", "stunt", "umbrella", "web", "million", "palm", "quit",
	"ethos", "ocean", "address", "future", "status", "taxi", "excess", "tender", "broom", "judge",
	"remain", "rival", "storm", "border", "life", "quite", "driven", "till", "fudge", "neutral",
	"separate", "six", "merely", "east", "media", "pale", "rally", "starve", "vessel", "high",
	"tell", "merge", "organ", "segment", "wrong", "navy", "hang", "loss", "bluff", "kite",
	"olive", "pipe", "spade", "nation", "ruling", "mayor", "onto", "felt", "cling", "could",
	"relief", "sibling", "exceed", "drop", "flame", "absence", "motion", "fuel", "ways", "bill",
	"grow", "title", "fall", "know", "play", "hunger", "spin", "crest", "hurry", "omit",
	"sleek", "split", "tissue", "virus", "titles", "came", "toll", "forge", "knead", "laser",
	"witness", "boom", "kind", "mars", "circus", "purse", "quake", "turned", "chaos", "grit",
	"welcome", "covers", "method", "fair", "mine", "boost", "brass", "harbor", "helmet", "mining",
	"idea", "mail", "next", "latch", "speck", "thing", "wed", "scarf", "weather", "window",
	"young", "belong", "bell", "fleet", "helm", "might", "swallow", "closet", "mortgage", "stadium",
	"hero", "stout", "code", "fund", "opinion", "resist", "trait", "ability", "unite", "decide",
	"yields", "pound", "zinc", "bear", "cease", "charm", "height", "trust", "vanish", "veal",
	"mutual", "thank", "whistle", "invest", "literal", "proven", "shorts", "worried", "disk", "attic",
	"mug", "myriad", "soap", "inch", "sole", "lure", "pour", "tend", "kitten", "lemon",
	"thunder", "trick", "unity", "info", "infer", "ladder", "funding", "member", "seem", "spot",
	"depth", "orbit", "attend", "occupy", "free", "retire", "borrow", "maxwell", "jury", "bench",
	"dingo", "focal", "liver", "noise", "oxide", "article", "well", "floor", "glyph", "prize",
	"format", "ground", "towers", "noun", "real", "peer", "senate", "shadow", "tie", "cast",
	"tech", "blood", "paint", "viable", "flying", "fossil", "booth", "drown", "also", "fill",
	"lots", "zero", "hub", "minor", "sack", "useful", "data", "made", "intro", "escape",
	"monitor", "really", "crash", "froze", "single", "ballot", "club", "oven", "glint", "lodge",
	"vibrant", "barrier", "boat", "edit", "ditch", "avenue", "famous", "once", "depot", "knob",
	"said", "usual", "pick", "snow", "test", "sling", "moon", "tape", "pant", "travel",
	"pretty", "wear", "decry", "sky", "statue", "stray", "suppose", "sail", "nadir", "reveal",
	"poetry", "wrist", "shield", "pool", "learn", "pearl", "tattoo", "rumor", "stomach", "send",
	"drift", "now", "old", "stack", "wreck", "bedroom", "ball", "beet", "roast", "stead",
	"taste", "golden", "shiny", "modern", "ether", "spell", "keen", "prose", "zebra", "exile",
	"soldier", "take", "task", "rigor", "speaker", "surround", "teeth", "slip", "wrap", "player",
	"blue", "save", "hammer", "summer", "chamber", "literary", "sign", "derby", "breeze", "sever",
	"sip", "visit", "energy", "null", "shy", "hawk", "mirth", "service", "square", "fairly",
	"held", "blurt", "dater", "jolly", "taught", "mode", "machine", "duty", "devon", "robot",
	"shove", "sprinkle", "arise", "defence", "face", "gear", "have", "ruth", "farce", "valid",
	"dream", "herb", "labour", "cinema", "remark", "tonight", "unveil", "both", "page", "choir",
	"ratio", "thread", "edge", "fire", "land", "lane", "prey", "spine", "sticky", "steam",
	"stroke", "good", "poet", "seek", "gossip", "subject", "swear", "gray", "sept", "midst",
	"pitch", "thick", "damage", "shares", "pulp", "spree", "tour", "local", "plain", "reef",
	"slate", "yarn", "sale", "lance", "stock", "verify", "bird", "jobs", "lapse", "queen",
	"stress", "wary", "weep", "gathering", "pace", "pact", "putt", "card", "open", "decor",
	"rudder", "cage", "cook", "fiend", "hungry", "odd", "expand", "cloth", "lobe", "panel",
	"hefty", "breach", "shoe", "urge", "expel", "graft", "haste", "humid", "thorn", "empire",
	"hidden", "crew", "grew", "chess", "fiber", "juice", "purple", "load", "lock", "broke",
	"fifty", "heavy", "poise", "table", "the", "flora", "clover", "revive", "whisper", "corner",
	"eleven", "exam", "wood", "remind", "current", "patent", "like", "click", "mobile", "new",
	"people", "radar", "recipe", "climb", "hatch", "prowl", "simple", "solid", "sponsor", "took",
	"maker", "scent", "spray", "suspect", "bishop", "side", "coast", "twelve", "cool", "desk",
	"mango", "drama", "grade", "centre", "failed", "craft", "flour", "harry", "loyal", "plum",
	"random", "social", "grace", "prompt", "video", "gazelle", "cell", "genre", "greet", "uniform",
	"plea", "champ", "daisy", "sales", "spoil", "hole", "knee", "lose", "onion", "parade",
	"peel", "while", "arrange", "dinner", "extend", "hand", "meet", "paper", "serial", "shark",
	"snack", "stool", "wedding", "hydra", "slide", "who", "treaty", "first", "frame", "unfold",
	"steady", "lack", "jiffy", "revise", "sing", "brought", "clean", "pause", "special", "debate",
	"loud", "steer", "park", "juror", "arbor", "chose", "stored", "lift", "equal", "fluid",
	"sir", "skirt", "gain", "team", "drape", "idiom", "runway", "author", "base", "burden",
	"wage", "wake", "wire", "buggy", "robust", "unique", "screen", "rinse", "sauce", "sugar",
	"supply", "loneliness", "sweat", "crawl", "quality", "rhyme", "speak", "mere", "mood", "tail",
	"grip", "thought", "build", "repeat", "vigor", "wanting", "porch", "search", "summit", "oxford",
	"mass", "dried", "gravy", "lawsuit", "permit", "where", "hunt", "were", "faint", "glove",
	"double", "blank", "paste", "pine", "slant", "eating", "thrown", "file", "apple", "beast",
	"tribe", "vocal", "suburb", "front", "marsh", "skull", "vote", "court", "tiger", "century",
	"tune", "vine", "viola", "nine", "seen", "gnome", "puppet", "soda", "stick", "vowel",
	"wink", "head", "rare", "quest", "ripe", "yield", "desire", "gulf", "blues", "piano",
	"renew", "slope", "more", "role", "mule", "petrol", "wander", "true", "zoo", "close",
	"rabbit", "tile", "bureau", "impair", "poem", "push", "mouse", "anywhere", "blush", "gavel",
	"receipt", "spice", "dear", "feet", "merit", "milky", "senior", "bloom", "diner", "shower",
	"whom", "drain", "false", "nerve", "flint", "kiwi", "strange", "down", "rent", "carol",
	"denim", "primal", "reason", "cheap", "robe", "comply", "city", "stir", "fable", "melon",
	"pulse", "start", "subway", "four", "laid", "love", "bring", "chill", "meant", "prism",
	"second", "price", "prone", "marked", "mark", "pump", "chalk", "check", "grind", "icon",
	"lemur", "outside", "cake", "rely", "word", "blimp", "lamb", "moss", "rib", "quartz",
	"flair", "report", "attempt", "figure", "nights", "poultry", "recent", "salt", "that", "class",
	"exact", "poppy", "recite", "shave", "throne", "grand", "seminar", "league", "remember", "fiery",
	"knot", "clove", "shrimp", "tongue", "trophy", "voice", "addition", "date", "item", "brief",
	"release", "tactic", "domain", "equity", "fellow", "line", "tire", "west", "clone", "indoor",
	"mount", "smash", "tube", "irony", "navel", "royal", "sorry", "part", "rise", "yard",
	"medal", "reduce", "riding", "field", "hardy", "rip", "slump", "spirit", "marine", "still",
	"menu", "pair", "eaten", "legal", "symbol", "mind", "rock", "doubt", "tornado", "size",
	"hedge", "steel", "blurb", "halt", "credit", "bank", "khaki", "pike", "row", "tram",
	"vest", "modem", "night", "fiscal", "email", "girth", "prune", "certain", "growth", "haze",
	"mystery", "toad", "width", "safe", "with", "cable", "thirst", "buddy", "degree", "toss",
	"hear", "pure", "they", "quail", "twine", "wheel", "affected", "wide", "beard", "buyer",
	"early", "nab", "sore", "help", "only", "lump", "miss", "scoop", "plaza", "scrub",
	"vein", "seal", "draw", "peril", "pupil", "thirty", "gate", "mesh", "rain", "couch",
	"hat", "ancient", "trends", "mill", "pass", "rush", "turn", "span", "tick", "means",
	"picture", "shred", "snore", "from", "golf", "gust", "lucky", "amused", "awesome", "beaming",
	"carefree", "cheerful", "cheery", "chipper", "delightful", "elated", "excellent", "fabulous", "friendly", "fun",
	"gleeful", "jovial", "joyful", "joyous", "jubilant", "kindness", "lively", "mellow", "peppy", "pleasant",
	"playful", "positive", "radiant", "upbeat", "almond", "apricot", "bagel", "brownie", "bubblegum", "butterscotch",
	"caramel", "cashew", "chocolate", "cinnamon", "cookie", "crumpet", "cupcake", "custard", "dumpling", "eclair",
	"fondue", "gingerbread", "gumdrop", "jellybean", "lemonade", "lollipop", "macaron", "macaroon", "marmalade", "marshmallow",
	"nectarine", "pancake", "papaya", "parfait", "peanut", "peppermint", "pickle", "popsicle", "raspberry", "strawberry",
	"taffy", "tangerine", "vanilla", "waffle", "watermelon", "zest", "zesty", "acorn", "airy", "bluebird",
	"brooklet", "buttercup", "cardinal", "cloverleaf", "daffodil", "dragonfly", "evergreen", "firefly", "flower", "foxglove",
	"honeybee", "hummingbird", "ladybug", "lavender", "meadow", "moonbeam", "moonlight", "pansy", "petunia", "raindrop",
	"robin", "rosy", "sprout", "starlight", "sunflower", "treetop", "wildflower", "woodland", "zephyr", "alpaca",
	"basenji", "beagle", "borzoi", "budgie", "calico", "capybara", "chinchilla", "chipmunk", "cockatiel", "collie",
	"corgi", "dachshund", "ferret", "finch", "gerbil", "goldendoodle", "goldfish", "greyhound", "guineapig", "hamster",
	"hedgehog", "labradoodle", "labrador", "manx", "meerkat", "otter", "papillon", "parakeet", "poodle", "puffin",
	"retriever", "saluki", "schnauzer", "setter", "shiba", "spaniel", "sparrow", "tabby", "terrier", "whippet",
	"wombat", "adventure", "amble", "babble", "balloon", "banjo", "boomerang", "bouncy", "carnival", "carousel",
	"celebrate", "checkers", "confetti", "dandy", "dapper", "dazzle", "daydream", "dominoes", "doodle", "firework",
	"frisbee", "frolic", "giggle", "hopscotch", "jigsaw", "jingle", "kazoo", "kiteboard", "marbles", "pinball",
	"pinwheel", "polka", "puzzle", "scooter", "sparkle", "trampoline", "twinkle", "ukulele", "zippy",
}
