#!/usr/bin/env bash
# Regenerate the pre-minted EXPIRED TLS certificate the invalid-certificate test
# relies on.
#
# The test needs a certificate that is already expired at test time so the
# extension server drops the listener that references it while sibling listeners
# keep serving. cert-manager cannot help here: it renews before expiry, so it
# cannot hold a certificate in the expired state. We instead mint a self-signed
# certificate whose validity window is in the past.
#
# This is a listener certificate for the customer hostname under test, entirely
# separate from the certificate authority securing the extension server's own
# connection to the gateway; do not wire it to that authority.
#
# Output: expired-cert-secret.yaml — a Secret with the expired certificate and
# key inline. The committed Secret is what the test consumes, so a live run needs
# no openssl; re-run this script only to refresh it.
#
# Usage: ./gen-certs.sh [HOSTNAME] [SECRET_NAME] [SECRET_NAMESPACE]
set -euo pipefail

HOST="${1:-bad.e2e.env.datum.net}"
SECRET_NAME="${2:-expired-leaf-tls}"
SECRET_NS="${3:-default}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

# ECDSA P-256 key.
openssl ecparam -name prime256v1 -genkey -noout -out "${WORK}/tls.key"

# A self-signed certificate whose validity window is entirely in the past. We set
# the exact start and end times with OpenSSL 3.x's -not_before/-not_after so the
# certificate is already expired by the time the test runs.
NOT_BEFORE="20260621000000Z"
NOT_AFTER="20260622000000Z"

cat > "${WORK}/leaf.cnf" <<EOF
[req]
distinguished_name = dn
prompt = no
x509_extensions = v3
[dn]
CN = ${HOST}
[v3]
subjectAltName = DNS:${HOST}
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
EOF

openssl req -new -x509 \
  -key "${WORK}/tls.key" \
  -out "${WORK}/tls.crt" \
  -config "${WORK}/leaf.cnf" \
  -not_before "${NOT_BEFORE}" \
  -not_after "${NOT_AFTER}" \
  -sha256

echo "minted leaf for ${HOST}:"
openssl x509 -in "${WORK}/tls.crt" -noout -subject -dates

CRT_B64="$(base64 < "${WORK}/tls.crt" | tr -d '\n')"
KEY_B64="$(base64 < "${WORK}/tls.key" | tr -d '\n')"

cat > "${SCRIPT_DIR}/expired-cert-secret.yaml" <<EOF
# GENERATED by gen-certs.sh — do not edit by hand; re-run the script to refresh.
#
# A pre-minted EXPIRED certificate for ${HOST}. Its validity window
# (${NOT_BEFORE} .. ${NOT_AFTER}) is in the past, so the extension server drops
# the listener that references it while sibling listeners keep serving.
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${SECRET_NS}
type: kubernetes.io/tls
data:
  tls.crt: ${CRT_B64}
  tls.key: ${KEY_B64}
EOF

echo "wrote ${SCRIPT_DIR}/expired-cert-secret.yaml"
