apiVersion: networking.datumapis.com/v1alpha
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: network-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicy-sample
spec:
  # TODO(user): Add fields here
