//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connector) DeepCopyInto(out *Connector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connector.
func (in *Connector) DeepCopy() *Connector {
	if in == nil {
		return nil
	}
	out := new(Connector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Connector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAdvertisement) DeepCopyInto(out *ConnectorAdvertisement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAdvertisement.
func (in *ConnectorAdvertisement) DeepCopy() *ConnectorAdvertisement {
	if in == nil {
		return nil
	}
	out := new(ConnectorAdvertisement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorAdvertisement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAdvertisementLayer4) DeepCopyInto(out *ConnectorAdvertisementLayer4) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ConnectorAdvertisementLayer4Service, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAdvertisementLayer4.
func (in *ConnectorAdvertisementLayer4) DeepCopy() *ConnectorAdvertisementLayer4 {
	if in == nil {
		return nil
	}
	out := new(ConnectorAdvertisementLayer4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAdvertisementLayer4Service) DeepCopyInto(out *ConnectorAdvertisementLayer4Service) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Layer4ServicePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAdvertisementLayer4Service.
func (in *ConnectorAdvertisementLayer4Service) DeepCopy() *ConnectorAdvertisementLayer4Service {
	if in == nil {
		return nil
	}
	out := new(ConnectorAdvertisementLayer4Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAdvertisementList) DeepCopyInto(out *ConnectorAdvertisementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectorAdvertisement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAdvertisementList.
func (in *ConnectorAdvertisementList) DeepCopy() *ConnectorAdvertisementList {
	if in == nil {
		return nil
	}
	out := new(ConnectorAdvertisementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorAdvertisementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAdvertisementSpec) DeepCopyInto(out *ConnectorAdvertisementSpec) {
	*out = *in
	out.ConnectorRef = in.ConnectorRef
	if in.Layer4 != nil {
		in, out := &in.Layer4, &out.Layer4
		*out = make([]ConnectorAdvertisementLayer4, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAdvertisementSpec.
func (in *ConnectorAdvertisementSpec) DeepCopy() *ConnectorAdvertisementSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorAdvertisementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAdvertisementStatus) DeepCopyInto(out *ConnectorAdvertisementStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAdvertisementStatus.
func (in *ConnectorAdvertisementStatus) DeepCopy() *ConnectorAdvertisementStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorAdvertisementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorCapability) DeepCopyInto(out *ConnectorCapability) {
	*out = *in
	if in.ConnectTCP != nil {
		in, out := &in.ConnectTCP, &out.ConnectTCP
		*out = new(ConnectorCapabilityConnectTCP)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorCapability.
func (in *ConnectorCapability) DeepCopy() *ConnectorCapability {
	if in == nil {
		return nil
	}
	out := new(ConnectorCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorCapabilityCommon) DeepCopyInto(out *ConnectorCapabilityCommon) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorCapabilityCommon.
func (in *ConnectorCapabilityCommon) DeepCopy() *ConnectorCapabilityCommon {
	if in == nil {
		return nil
	}
	out := new(ConnectorCapabilityCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorCapabilityConnectTCP) DeepCopyInto(out *ConnectorCapabilityConnectTCP) {
	*out = *in
	out.ConnectorCapabilityCommon = in.ConnectorCapabilityCommon
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorCapabilityConnectTCP.
func (in *ConnectorCapabilityConnectTCP) DeepCopy() *ConnectorCapabilityConnectTCP {
	if in == nil {
		return nil
	}
	out := new(ConnectorCapabilityConnectTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorCapabilityStatus) DeepCopyInto(out *ConnectorCapabilityStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorCapabilityStatus.
func (in *ConnectorCapabilityStatus) DeepCopy() *ConnectorCapabilityStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorCapabilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorClass) DeepCopyInto(out *ConnectorClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorClass.
func (in *ConnectorClass) DeepCopy() *ConnectorClass {
	if in == nil {
		return nil
	}
	out := new(ConnectorClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorClassList) DeepCopyInto(out *ConnectorClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectorClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorClassList.
func (in *ConnectorClassList) DeepCopy() *ConnectorClassList {
	if in == nil {
		return nil
	}
	out := new(ConnectorClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorClassSpec) DeepCopyInto(out *ConnectorClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorClassSpec.
func (in *ConnectorClassSpec) DeepCopy() *ConnectorClassSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorClassStatus) DeepCopyInto(out *ConnectorClassStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorClassStatus.
func (in *ConnectorClassStatus) DeepCopy() *ConnectorClassStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorConnectionDetails) DeepCopyInto(out *ConnectorConnectionDetails) {
	*out = *in
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = new(ConnectorConnectionDetailsPublicKey)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorConnectionDetails.
func (in *ConnectorConnectionDetails) DeepCopy() *ConnectorConnectionDetails {
	if in == nil {
		return nil
	}
	out := new(ConnectorConnectionDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorConnectionDetailsPublicKey) DeepCopyInto(out *ConnectorConnectionDetailsPublicKey) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]PublicKeyConnectorAddress, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorConnectionDetailsPublicKey.
func (in *ConnectorConnectionDetailsPublicKey) DeepCopy() *ConnectorConnectionDetailsPublicKey {
	if in == nil {
		return nil
	}
	out := new(ConnectorConnectionDetailsPublicKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorList) DeepCopyInto(out *ConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Connector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorList.
func (in *ConnectorList) DeepCopy() *ConnectorList {
	if in == nil {
		return nil
	}
	out := new(ConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorSpec) DeepCopyInto(out *ConnectorSpec) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]ConnectorCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorSpec.
func (in *ConnectorSpec) DeepCopy() *ConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorStatus) DeepCopyInto(out *ConnectorStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]ConnectorCapabilityStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConnectionDetails != nil {
		in, out := &in.ConnectionDetails, &out.ConnectionDetails
		*out = new(ConnectorConnectionDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.LeaseRef != nil {
		in, out := &in.LeaseRef, &out.LeaseRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorStatus.
func (in *ConnectorStatus) DeepCopy() *ConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Layer4ServicePort) DeepCopyInto(out *Layer4ServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Layer4ServicePort.
func (in *Layer4ServicePort) DeepCopy() *Layer4ServicePort {
	if in == nil {
		return nil
	}
	out := new(Layer4ServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalConnectorReference) DeepCopyInto(out *LocalConnectorReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalConnectorReference.
func (in *LocalConnectorReference) DeepCopy() *LocalConnectorReference {
	if in == nil {
		return nil
	}
	out := new(LocalConnectorReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicKeyConnectorAddress) DeepCopyInto(out *PublicKeyConnectorAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicKeyConnectorAddress.
func (in *PublicKeyConnectorAddress) DeepCopy() *PublicKeyConnectorAddress {
	if in == nil {
		return nil
	}
	out := new(PublicKeyConnectorAddress)
	in.DeepCopyInto(out)
	return out
}
