---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: envoy-gateway-extension-server-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway-extension-server-ca
spec:
  isCA: true
  commonName: envoy-gateway-extension-server-ca
  secretName: envoy-gateway-extension-server-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: envoy-gateway-extension-server-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: envoy-gateway-extension-server
spec:
  ca:
    secretName: envoy-gateway-extension-server-ca
