---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: datum-downstream-gateway
spec:
  mergeGateways: true
  ipFamily: DualStack
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
          volumes:
            - name: coraza-waf
              emptyDir: {}
        container:
          image: envoyproxy/envoy:contrib-v1.35.0
          volumeMounts:
            - name: coraza-waf
              mountPath: /opt/coraza-waf
        initContainers:
          - name: coraza-waf
            image: ghcr.io/datum-labs/coraza-envoy-go-filter/coraza-waf:v1.3.0-alpha10
            imagePullPolicy: IfNotPresent
            command:
              - cp
              - /coraza-waf.so
              - /opt/coraza-waf/
            volumeMounts:
              - name: coraza-waf
                mountPath: /opt/coraza-waf
      envoyService:
        externalTrafficPolicy: Cluster
        type: NodePort
        patch:
          type: StrategicMerge
          value:
            spec:
              ipFamilyPolicy: RequireDualStack
              ports:
                - name: http-80
                  nodePort: 30080
                  port: 80
                - name: https-443
                  nodePort: 30443
                  port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: datum-downstream-gateway
spec:
  controllerName: gateway.envoyproxy.io/datum-downstream-gateway
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: datum-downstream-gateway
    namespace: datum-downstream-gateway
