apiVersion: quota.miloapis.com/v1alpha1
kind: ClaimCreationPolicy
metadata:
  name: project-network-claim-policy
  labels:
    app.kubernetes.io/name: network-services-operator
    app.kubernetes.io/component: quota-system
spec:
  trigger:
    resource:
      apiVersion: networking.datumapis.com/v1alpha
      kind: Network
  target:
    resourceClaimTemplate:
      metadata:
        name: "network-{{ trigger.metadata.name }}"
        namespace: "{{requestInfo.namespace}}"
        labels:
          app.kubernetes.io/name: network-services-operator
          app.kubernetes.io/component: quota-system
        annotations:
          kubernetes.io/description: "Automatic quota claim for Network creation"
      spec:
        requests:
          - resourceType: networking.datumapis.com/networks
            amount: 1
