---
apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: gateway.envoyproxy.io-httproutefilters
spec:
  serviceRef:
    name: "gateway.envoyproxy.io"
  kind: HTTPRouteFilter
  plural: httproutefilters
  singular: httproutefilter
  permissions:
    - list
    - get
    - watch
    - create
    - update
    - patch
    - delete
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
