apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: networking.datumapis.com-networkservice
spec:
  serviceRef:
    name: "networking.datumapis.com"
  kind: NetworkService
  plural: networkservices
  singular: networkservice
  permissions:
    - list
    - get
    - create
    - update
    - patch
    - watch
    - delete
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
