apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: networking.datumapis.com-networkcontext
spec:
  serviceRef:
    name: "networking.datumapis.com"
  kind: NetworkContext
  plural: networkcontexts
  singular: networkcontext
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: networking.datumapis.com
      kind: Network
