apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: networking.datumapis.com-networkinterface
spec:
  serviceRef:
    name: "networking.datumapis.com"
  kind: NetworkInterface
  plural: networkinterfaces
  singular: networkinterface
  permissions:
    - list
    - get
    - create
    - update
    - patch
    - watch
    - delete
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
