apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

sortOptions:
  order: fifo

resources:
  - backend-registration.yaml
  - backendtlspolicy-registration.yaml
  - backendtrafficpolicy-registration.yaml
  - connector-registration.yaml
  - connectoradvertisement-registration.yaml
  - domain-registration.yaml
  - endpointslice-registration.yaml
  - gateway-registration.yaml
  - httpproxy-registration.yaml
  - httproute-registration.yaml
  - httproutefilter-registration.yaml
  - network-registration.yaml
  - networkpolicy-registration.yaml
  - securitypolicy-registration.yaml
  - trafficprotectionpolicy-registration.yaml
