apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network-services-operator-system

resources:
  - namespace.yaml
  - ../crd
  - ../rbac
  - service_account.yaml

components:
  - ../rbac_deployment
  - ../components/cell-controllers
