apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nso-slo
  namespace: nso-slo
spec:
  groups:
  - name: nso-slo
    interval: 30s
    rules:  
    - alert: GatewayNotReadySLOViolation
      expr: |
        (time() - datum_cloud_networking_gateway_created) > 60
        unless ignoring(type) (
          (datum_cloud_networking_gateway_status{type="Accepted"} == 1) and 
          (datum_cloud_networking_gateway_status{type="Programmed"} == 1)
        )
      for: 0s
      labels:
        severity: critical
        slo_violation: "true"
      annotations:
        summary: "Gateway {{ $labels.name }} is taking longer than 60 seconds to reach Ready status"
        description: "Gateway {{ $labels.name }} in namespace {{ $labels.namespace }} has been in creation state for {{ $value }} seconds without reaching Ready status (Accepted=True AND Programmed=True), which exceeds the 60-second SLO threshold."

    - alert: GatewayDegradedSLOViolation
      expr: |
        (
          (time() - datum_cloud_networking_gateway_status_condition_last_transition_time{type="Accepted", status="False"}) > 60
        ) or (
          (time() - datum_cloud_networking_gateway_status_condition_last_transition_time{type="Programmed", status="False"}) > 60
        )
      for: 0s
      labels:
        severity: critical
        slo_violation: "true"
      annotations:
        summary: "Gateway {{ $labels.name }} has been degraded for over 60 seconds"
        description: "Gateway {{ $labels.name }} in namespace {{ $labels.namespace }} has been in a degraded state (Accepted=False or Programmed=False) for {{ $value }} seconds without recovering, which exceeds the 60-second SLO threshold."