apiVersion: apiserver.config.datumapis.com/v1alpha1
kind: NetworkServicesOperator
metricsServer:
  bindAddress: "0"

webhookServer:
  port: 9444
  tls:
    secretRef:
      name: network-services-operator-webhook-server-cert
      namespace: kube-system

gateway:
  targetDomain: prism.e2e.env.datum.net
  downstreamGatewayClassName: datum-downstream-gateway
  downstreamGatewayNamespace: datum-downstream-gateway
  permittedTLSOptions:
    gateway.networking.datumapis.com/certificate-issuer: []
  listenerTLSOptions:
    gateway.networking.datumapis.com/certificate-issuer: auto
  httpRoutes:
    allowServiceBackends: true

httpProxy:
  gatewayClassName: network-services-operator-datum-external-global-proxy

downstreamResourceManagement:
  # TODO(jreese) remove this when we make the downstream resource strategy
  # configurable
  kubeconfigPath: ./infra.kubeconfig
