//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	"go.datum.net/network-services-operator/api/v1alpha"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHostnameAllowListEntry) DeepCopyInto(out *CustomHostnameAllowListEntry) {
	*out = *in
	if in.Suffixes != nil {
		in, out := &in.Suffixes, &out.Suffixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHostnameAllowListEntry.
func (in *CustomHostnameAllowListEntry) DeepCopy() *CustomHostnameAllowListEntry {
	if in == nil {
		return nil
	}
	out := new(CustomHostnameAllowListEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryConfig) DeepCopyInto(out *DiscoveryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryConfig.
func (in *DiscoveryConfig) DeepCopy() *DiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(DiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainVerificationConfig) DeepCopyInto(out *DomainVerificationConfig) {
	*out = *in
	if in.RetryIntervals != nil {
		in, out := &in.RetryIntervals, &out.RetryIntervals
		*out = make([]RetryInterval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainVerificationConfig.
func (in *DomainVerificationConfig) DeepCopy() *DomainVerificationConfig {
	if in == nil {
		return nil
	}
	out := new(DomainVerificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamResourceManagementConfig) DeepCopyInto(out *DownstreamResourceManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamResourceManagementConfig.
func (in *DownstreamResourceManagementConfig) DeepCopy() *DownstreamResourceManagementConfig {
	if in == nil {
		return nil
	}
	out := new(DownstreamResourceManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]v1alpha.IPFamily, len(*in))
		copy(*out, *in)
	}
	if in.PermittedTLSOptions != nil {
		in, out := &in.PermittedTLSOptions, &out.PermittedTLSOptions
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.ClusterIssuerMap != nil {
		in, out := &in.ClusterIssuerMap, &out.ClusterIssuerMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ValidPortNumbers != nil {
		in, out := &in.ValidPortNumbers, &out.ValidPortNumbers
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ValidProtocolTypes != nil {
		in, out := &in.ValidProtocolTypes, &out.ValidProtocolTypes
		*out = make(map[int][]apisv1.ProtocolType, len(*in))
		for key, val := range *in {
			var outVal []apisv1.ProtocolType
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]apisv1.ProtocolType, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProxyConfig) DeepCopyInto(out *HTTPProxyConfig) {
	*out = *in
	if in.GatewayTLSOptions != nil {
		in, out := &in.GatewayTLSOptions, &out.GatewayTLSOptions
		*out = make(map[apisv1.AnnotationKey]apisv1.AnnotationValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProxyConfig.
func (in *HTTPProxyConfig) DeepCopy() *HTTPProxyConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsServerConfig) DeepCopyInto(out *MetricsServerConfig) {
	*out = *in
	if in.SecureServing != nil {
		in, out := &in.SecureServing, &out.SecureServing
		*out = new(bool)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsServerConfig.
func (in *MetricsServerConfig) DeepCopy() *MetricsServerConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkServicesOperator) DeepCopyInto(out *NetworkServicesOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.MetricsServer.DeepCopyInto(&out.MetricsServer)
	in.WebhookServer.DeepCopyInto(&out.WebhookServer)
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.HTTPProxy.DeepCopyInto(&out.HTTPProxy)
	out.Discovery = in.Discovery
	out.DownstreamResourceManagement = in.DownstreamResourceManagement
	in.DomainVerification.DeepCopyInto(&out.DomainVerification)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkServicesOperator.
func (in *NetworkServicesOperator) DeepCopy() *NetworkServicesOperator {
	if in == nil {
		return nil
	}
	out := new(NetworkServicesOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkServicesOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryInterval) DeepCopyInto(out *RetryInterval) {
	*out = *in
	out.Interval = in.Interval
	if in.MaxElapsed != nil {
		in, out := &in.MaxElapsed, &out.MaxElapsed
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryInterval.
func (in *RetryInterval) DeepCopy() *RetryInterval {
	if in == nil {
		return nil
	}
	out := new(RetryInterval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookServerConfig) DeepCopyInto(out *WebhookServerConfig) {
	*out = *in
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookServerConfig.
func (in *WebhookServerConfig) DeepCopy() *WebhookServerConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookServerConfig)
	in.DeepCopyInto(out)
	return out
}
