//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	"go.datum.net/network-services-operator/api/v1alpha"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendTrafficPolicyValidationOptions) DeepCopyInto(out *BackendTrafficPolicyValidationOptions) {
	*out = *in
	in.ClusterSettings.DeepCopyInto(&out.ClusterSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendTrafficPolicyValidationOptions.
func (in *BackendTrafficPolicyValidationOptions) DeepCopy() *BackendTrafficPolicyValidationOptions {
	if in == nil {
		return nil
	}
	out := new(BackendTrafficPolicyValidationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSettingsValidationOptions) DeepCopyInto(out *ClusterSettingsValidationOptions) {
	*out = *in
	if in.TCPKeepaliveMinIdleTime != nil {
		in, out := &in.TCPKeepaliveMinIdleTime, &out.TCPKeepaliveMinIdleTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.TCPKeepaliveMinInterval != nil {
		in, out := &in.TCPKeepaliveMinInterval, &out.TCPKeepaliveMinInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.TCPMaxConnectionTimeout != nil {
		in, out := &in.TCPMaxConnectionTimeout, &out.TCPMaxConnectionTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HTTPMaxConnectionIdleTimeout != nil {
		in, out := &in.HTTPMaxConnectionIdleTimeout, &out.HTTPMaxConnectionIdleTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HTTPMaxConnectionDuration != nil {
		in, out := &in.HTTPMaxConnectionDuration, &out.HTTPMaxConnectionDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HTTPMaxRequestTimeout != nil {
		in, out := &in.HTTPMaxRequestTimeout, &out.HTTPMaxRequestTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ConnectionMaxBufferLimit != nil {
		in, out := &in.ConnectionMaxBufferLimit, &out.ConnectionMaxBufferLimit
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DNSMinRefreshRate != nil {
		in, out := &in.DNSMinRefreshRate, &out.DNSMinRefreshRate
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HTTP2MaxInitialStreamWindowSize != nil {
		in, out := &in.HTTP2MaxInitialStreamWindowSize, &out.HTTP2MaxInitialStreamWindowSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.HTTP2MaxInitialConnectionWindowSize != nil {
		in, out := &in.HTTP2MaxInitialConnectionWindowSize, &out.HTTP2MaxInitialConnectionWindowSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSettingsValidationOptions.
func (in *ClusterSettingsValidationOptions) DeepCopy() *ClusterSettingsValidationOptions {
	if in == nil {
		return nil
	}
	out := new(ClusterSettingsValidationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorConfig) DeepCopyInto(out *ConnectorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorConfig.
func (in *ConnectorConfig) DeepCopy() *ConnectorConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorazaConfig) DeepCopyInto(out *CorazaConfig) {
	*out = *in
	if in.ListenerDirectives != nil {
		in, out := &in.ListenerDirectives, &out.ListenerDirectives
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RouteBaseDirectives != nil {
		in, out := &in.RouteBaseDirectives, &out.RouteBaseDirectives
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorazaConfig.
func (in *CorazaConfig) DeepCopy() *CorazaConfig {
	if in == nil {
		return nil
	}
	out := new(CorazaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHostnameAllowListEntry) DeepCopyInto(out *CustomHostnameAllowListEntry) {
	*out = *in
	if in.Suffixes != nil {
		in, out := &in.Suffixes, &out.Suffixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHostnameAllowListEntry.
func (in *CustomHostnameAllowListEntry) DeepCopy() *CustomHostnameAllowListEntry {
	if in == nil {
		return nil
	}
	out := new(CustomHostnameAllowListEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryConfig) DeepCopyInto(out *DiscoveryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryConfig.
func (in *DiscoveryConfig) DeepCopy() *DiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(DiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainRegistrationConfig) DeepCopyInto(out *DomainRegistrationConfig) {
	*out = *in
	if in.RefreshInterval != nil {
		in, out := &in.RefreshInterval, &out.RefreshInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RetryBackoff != nil {
		in, out := &in.RetryBackoff, &out.RetryBackoff
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.LookupTimeout != nil {
		in, out := &in.LookupTimeout, &out.LookupTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	in.RegistryData.DeepCopyInto(&out.RegistryData)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainRegistrationConfig.
func (in *DomainRegistrationConfig) DeepCopy() *DomainRegistrationConfig {
	if in == nil {
		return nil
	}
	out := new(DomainRegistrationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainVerificationConfig) DeepCopyInto(out *DomainVerificationConfig) {
	*out = *in
	if in.RetryIntervals != nil {
		in, out := &in.RetryIntervals, &out.RetryIntervals
		*out = make([]RetryInterval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainVerificationConfig.
func (in *DomainVerificationConfig) DeepCopy() *DomainVerificationConfig {
	if in == nil {
		return nil
	}
	out := new(DomainVerificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamResourceManagementConfig) DeepCopyInto(out *DownstreamResourceManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamResourceManagementConfig.
func (in *DownstreamResourceManagementConfig) DeepCopy() *DownstreamResourceManagementConfig {
	if in == nil {
		return nil
	}
	out := new(DownstreamResourceManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionAPIValidationOptions) DeepCopyInto(out *ExtensionAPIValidationOptions) {
	*out = *in
	in.BackendTrafficPolicies.DeepCopyInto(&out.BackendTrafficPolicies)
	out.HTTPRouteFilters = in.HTTPRouteFilters
	in.SecurityPolicies.DeepCopyInto(&out.SecurityPolicies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionAPIValidationOptions.
func (in *ExtensionAPIValidationOptions) DeepCopy() *ExtensionAPIValidationOptions {
	if in == nil {
		return nil
	}
	out := new(ExtensionAPIValidationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]v1alpha.IPFamily, len(*in))
		copy(*out, *in)
	}
	if in.PermittedTLSOptions != nil {
		in, out := &in.PermittedTLSOptions, &out.PermittedTLSOptions
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.ClusterIssuerMap != nil {
		in, out := &in.ClusterIssuerMap, &out.ClusterIssuerMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ListenerTLSOptions != nil {
		in, out := &in.ListenerTLSOptions, &out.ListenerTLSOptions
		*out = make(map[apisv1.AnnotationKey]apisv1.AnnotationValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Coraza.DeepCopyInto(&out.Coraza)
	if in.ValidPortNumbers != nil {
		in, out := &in.ValidPortNumbers, &out.ValidPortNumbers
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ValidProtocolTypes != nil {
		in, out := &in.ValidProtocolTypes, &out.ValidProtocolTypes
		*out = make(map[int][]apisv1.ProtocolType, len(*in))
		for key, val := range *in {
			var outVal []apisv1.ProtocolType
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]apisv1.ProtocolType, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	in.ExtensionAPIValidationOptions.DeepCopyInto(&out.ExtensionAPIValidationOptions)
	out.HTTPRoutes = in.HTTPRoutes
	in.ResourceReplicator.DeepCopyInto(&out.ResourceReplicator)
	if in.DeleteErroredChallenges != nil {
		in, out := &in.DeleteErroredChallenges, &out.DeleteErroredChallenges
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayResourceReplicatorConfig) DeepCopyInto(out *GatewayResourceReplicatorConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ReplicatedResourceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayResourceReplicatorConfig.
func (in *GatewayResourceReplicatorConfig) DeepCopy() *GatewayResourceReplicatorConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayResourceReplicatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProxyConfig) DeepCopyInto(out *HTTPProxyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProxyConfig.
func (in *HTTPProxyConfig) DeepCopy() *HTTPProxyConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteValidationOptions) DeepCopyInto(out *HTTPRouteValidationOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteValidationOptions.
func (in *HTTPRouteValidationOptions) DeepCopy() *HTTPRouteValidationOptions {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteValidationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderElectionConfig) DeepCopyInto(out *LeaderElectionConfig) {
	*out = *in
	out.LeaseDuration = in.LeaseDuration
	out.RenewDeadline = in.RenewDeadline
	out.RetryPeriod = in.RetryPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionConfig.
func (in *LeaderElectionConfig) DeepCopy() *LeaderElectionConfig {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsServerConfig) DeepCopyInto(out *MetricsServerConfig) {
	*out = *in
	if in.SecureServing != nil {
		in, out := &in.SecureServing, &out.SecureServing
		*out = new(bool)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsServerConfig.
func (in *MetricsServerConfig) DeepCopy() *MetricsServerConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkServicesOperator) DeepCopyInto(out *NetworkServicesOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.MetricsServer.DeepCopyInto(&out.MetricsServer)
	in.WebhookServer.DeepCopyInto(&out.WebhookServer)
	in.Gateway.DeepCopyInto(&out.Gateway)
	out.HTTPProxy = in.HTTPProxy
	out.Connector = in.Connector
	out.Discovery = in.Discovery
	out.DownstreamResourceManagement = in.DownstreamResourceManagement
	in.Redis.DeepCopyInto(&out.Redis)
	out.LeaderElection = in.LeaderElection
	in.DomainVerification.DeepCopyInto(&out.DomainVerification)
	in.DomainRegistration.DeepCopyInto(&out.DomainRegistration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkServicesOperator.
func (in *NetworkServicesOperator) DeepCopy() *NetworkServicesOperator {
	if in == nil {
		return nil
	}
	out := new(NetworkServicesOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkServicesOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCValidationOptions) DeepCopyInto(out *OIDCValidationOptions) {
	*out = *in
	if in.MinRefreshTokenTTL != nil {
		in, out := &in.MinRefreshTokenTTL, &out.MinRefreshTokenTTL
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCValidationOptions.
func (in *OIDCValidationOptions) DeepCopy() *OIDCValidationOptions {
	if in == nil {
		return nil
	}
	out := new(OIDCValidationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisConfig) DeepCopyInto(out *RedisConfig) {
	*out = *in
	if in.DialTimeout != nil {
		in, out := &in.DialTimeout, &out.DialTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.WriteTimeout != nil {
		in, out := &in.WriteTimeout, &out.WriteTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisConfig.
func (in *RedisConfig) DeepCopy() *RedisConfig {
	if in == nil {
		return nil
	}
	out := new(RedisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryDataCacheConfig) DeepCopyInto(out *RegistryDataCacheConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryDataCacheConfig.
func (in *RegistryDataCacheConfig) DeepCopy() *RegistryDataCacheConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryDataCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryDataCacheTTLsConfig) DeepCopyInto(out *RegistryDataCacheTTLsConfig) {
	*out = *in
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Nameserver != nil {
		in, out := &in.Nameserver, &out.Nameserver
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.IPRegistrant != nil {
		in, out := &in.IPRegistrant, &out.IPRegistrant
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryDataCacheTTLsConfig.
func (in *RegistryDataCacheTTLsConfig) DeepCopy() *RegistryDataCacheTTLsConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryDataCacheTTLsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryDataConfig) DeepCopyInto(out *RegistryDataConfig) {
	*out = *in
	out.Cache = in.Cache
	in.CacheTTLs.DeepCopyInto(&out.CacheTTLs)
	in.RateLimits.DeepCopyInto(&out.RateLimits)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryDataConfig.
func (in *RegistryDataConfig) DeepCopy() *RegistryDataConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryDataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryDataRateLimitsConfig) DeepCopyInto(out *RegistryDataRateLimitsConfig) {
	*out = *in
	if in.DefaultBlock != nil {
		in, out := &in.DefaultBlock, &out.DefaultBlock
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryDataRateLimitsConfig.
func (in *RegistryDataRateLimitsConfig) DeepCopy() *RegistryDataRateLimitsConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryDataRateLimitsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedResourceConfig) DeepCopyInto(out *ReplicatedResourceConfig) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedResourceConfig.
func (in *ReplicatedResourceConfig) DeepCopy() *ReplicatedResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ReplicatedResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryInterval) DeepCopyInto(out *RetryInterval) {
	*out = *in
	out.Interval = in.Interval
	if in.MaxElapsed != nil {
		in, out := &in.MaxElapsed, &out.MaxElapsed
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryInterval.
func (in *RetryInterval) DeepCopy() *RetryInterval {
	if in == nil {
		return nil
	}
	out := new(RetryInterval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityPolicyValidationOptions) DeepCopyInto(out *SecurityPolicyValidationOptions) {
	*out = *in
	out.APIKeyAuth = in.APIKeyAuth
	out.CORS = in.CORS
	out.JWTProvider = in.JWTProvider
	in.OIDC.DeepCopyInto(&out.OIDC)
	out.Authorization = in.Authorization
	in.ClusterSettings.DeepCopyInto(&out.ClusterSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityPolicyValidationOptions.
func (in *SecurityPolicyValidationOptions) DeepCopy() *SecurityPolicyValidationOptions {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicyValidationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookServerConfig) DeepCopyInto(out *WebhookServerConfig) {
	*out = *in
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookServerConfig.
func (in *WebhookServerConfig) DeepCopy() *WebhookServerConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookServerConfig)
	in.DeepCopyInto(out)
	return out
}
