version: '3'

tasks:
  dev:
    desc: Run the UI development server
    cmds:
      - npm run dev

  build:
    desc: Build the UI for production
    cmds:
      - npm run build

  lint:
    desc: Run linting
    cmds:
      - npm run lint

  install:
    desc: Install dependencies
    cmds:
      - npm install
