apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-services-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: network-services-operator
      app.kubernetes.io/part-of: datum-control-plane
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-services-operator
        app.kubernetes.io/part-of: datum-control-plane
    spec:
      automountServiceAccountToken: false
      containers:
        image: us-east4-docker.pkg.dev/datum-cloud-prod/datum-internal-images/network-services-operator:v0.0.1-v1alpha1-amd64
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: network-services-operator
        ports:
        - containerPort: 8081
          name: health
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        resources: {}
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - apply
        - --kubeconfig=/etc/kubernetes/auth/network-services-operator.kubeconfig
        - -f
        - /crd
        image: us-east4-docker.pkg.dev/datum-cloud-prod/datum-internal-images/network-services-operator-crds:v0.0.1-v1alpha1-amd64
        imagePullPolicy: IfNotPresent
        name: install-crds
        resources: {}
        securityContext:
          runAsGroup: 65532
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30