name: Publish Docker Image

on:
  push:
  release:
    types: ['published']

jobs:
  publish:
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.0.0
    with:
      image-name: network-services-operator
    secrets: inherit

  publish-kustomize-bundles:
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      matrix:
        bundles:
          - name: ghcr.io/datum-cloud/network-services-operator/network-services-crds
            path: config/crd
          - name: ghcr.io/datum-cloud/network-services-operator/network-services-operator
            path: config/network-services-operator
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.1.0
    with:
      bundle-name: ${{ matrix.bundles.name }}
      bundle-path: ${{ matrix.bundles.path }}
    secrets: inherit