apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # networking.datumapis.com kinds
  - httpproxy-policy.yaml
  - domain-policy.yaml
  - connector-policy.yaml
  - connectoradvertisement-policy.yaml
  - trafficprotectionpolicy-policy.yaml
  # gateway.networking.k8s.io kinds
  - gateway-policy.yaml
  - httproute-policy.yaml
  - tcproute-policy.yaml
  - udproute-policy.yaml
  - tlsroute-policy.yaml
  - backendtlspolicy-policy.yaml
